// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQvik9zup99sheBPaz1TqrghA8snp5Ul4',
    appId: '1:591122706669:web:20db396102d38ac9849ce4',
    messagingSenderId: '591122706669',
    projectId: 'mobilecc1',
    authDomain: 'mobilecc1.firebaseapp.com',
    storageBucket: 'mobilecc1.firebasestorage.app',
    measurementId: 'G-V7Q8QV50FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPZ456QFabXTm0gOlGAPy7gzv7BR2Wb5Q',
    appId: '1:591122706669:android:b04430bc7ae02c62849ce4',
    messagingSenderId: '591122706669',
    projectId: 'mobilecc1',
    storageBucket: 'mobilecc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrO8VwEzNtmASgBdfC33dAJTAFUMGVzAY',
    appId: '1:591122706669:ios:745e0dcc5050a381849ce4',
    messagingSenderId: '591122706669',
    projectId: 'mobilecc1',
    storageBucket: 'mobilecc1.firebasestorage.app',
    iosBundleId: 'com.example.firestoreAgain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrO8VwEzNtmASgBdfC33dAJTAFUMGVzAY',
    appId: '1:591122706669:ios:745e0dcc5050a381849ce4',
    messagingSenderId: '591122706669',
    projectId: 'mobilecc1',
    storageBucket: 'mobilecc1.firebasestorage.app',
    iosBundleId: 'com.example.firestoreAgain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQvik9zup99sheBPaz1TqrghA8snp5Ul4',
    appId: '1:591122706669:web:5e4762f4088b1c82849ce4',
    messagingSenderId: '591122706669',
    projectId: 'mobilecc1',
    authDomain: 'mobilecc1.firebaseapp.com',
    storageBucket: 'mobilecc1.firebasestorage.app',
    measurementId: 'G-CQK9BQSZ45',
  );
}
